### ISSUE TITLE
Erratic sorting by Notes column

### ISSUE THREAD

**Issue by martinprikryl** [manugarg/pagenotes-issues#10]
With some specific contents of Notes, sorting by _Notes_ column on _All Notes_ view behaves erratically.
This is example of Notes that can be used to reproduce the problem: [pagenotes.csv](https://github.com/manugarg/pagenotes-issues/files/7834664/pagenotes.csv)

When I sort by _Notes_ column the first time, no sorting happens (only the sorting arrow at the heading changes):
![image](https://user-images.githubusercontent.com/1632297/148674629-0d02954b-9b7d-41e2-8433-6af89c68e939.png)

When I click the _Notes_ heading the second time, the list order is reversed, but it is still not sorted (at least not by any criteria I can identify):
![image](https://user-images.githubusercontent.com/1632297/148674620-672604d2-e1d8-4930-a21e-5794e590810e.png)

When I click the _Notes_ heading the third time, nothing happens (except for reverting the direction of the arrow):
![image](https://user-images.githubusercontent.com/1632297/148674745-90b20db2-80d3-41ef-8cf1-f8d5a836c703.png)

When I click the _Notes_ heading the fourth time, I get back to the first state.

Interestingly, when I remove dashes from the Notes (_"20220125 aaa"_, etc), the sorting works as expected.

I've tried it with various Regional settings in Windows (including US English), but it does not seem affect the behavior.

Thanks for looking into this. And mainly thanks for the extension!

**Comment by manugarg** [comment]
@martinprikryl Thanks a lot for reporting this. Looks like latest sorting table javascript has fixed this issue. I updated it recently.
