### ISSUE TITLE
Make page notes popup window size configurable

### ISSUE THREAD

**Issue by manugarg** [manugarg/pagenotes-issues#11]
From the support page:

> Hi, Can you please give us an option to set the width and height of the popup window? currently, it is hardly 200-300px, and difficult to save and browse the content, and often the length goes vertically and hard to scroll up and down. I want it to be wider, at least 500-800px. Please put this in the options.html itself and let us configure. Thanks.
> Posted by Veeresh Devireddy - 2 weeks ago

**Comment by drveresh** [comment]
Hi @manugarg, do you have any update on that issue?  Please put a fix for that. It is becoming a painful experience to scroll down several pages of notes per domain, within that small 100px width window.

**Comment by manugarg** [comment]
> Hi @manugarg, do you have any update on that issue?

I am working on it. I'll release it soon.


> Please put a fix for that. It is becoming a painful experience to scroll down several pages of notes per domain, within that small 100px width window.

Width is actually 256px right now.

**Comment by drveresh** [comment]
Thanks for the quick response.  Sorry, 100px was a guess.  I am using Mac with display of "15.4-inch (2880 × 1800)", so 256px is really insufficient.

**Comment by manugarg** [comment]
Heads up -- extension package has been submitted for review. For whatever reason, it's taking long. I'll update here once it's published.

**Comment by drveresh** [comment]
Thank you @manugarg for enhancing it.
