### ISSUE TITLE
More prominent icon

### ISSUE THREAD

**Issue by huyz** [manugarg/pagenotes-issues#16]
I feel like yellow shaded icon isn't noticeable enough.

I don't really remember which sites I've added notes for.  I'd like to be notified in a way—something to the effect of "Hey, did you know you have notes in this site that you visited a long time ago? So it would be great if the yellow icon were nice and in your face, e.g. a big red dot/badge on it.

Right now, I don't notice the yellow shading, especially next to the bright orange shield icon that Brave uses.

**Comment by manugarg** [comment]
This is solved in multiple ways now:
- Icon animates when you've a note for the site. (default: on)
- Now we show an icon badge as well. (default: on)
- You can now configure the extension to automatically show popup if page has a note. (default: off)

See https://pagenotes.manugarg.com/faq/ for more details.

**Comment by hrldcpr** [comment]
Awesome! If it's not a huge hassle, perhaps you could port some of these features over to the Firefox plugin as well? (If they're already there, I failed to find them.)

I know you probably have far fewer Firefox users, so no worries if not. Thanks either way for the great extension.
