### ISSUE TITLE
Sync not working in Incognito browser

### ISSUE THREAD

**Issue by drveresh** [manugarg/pagenotes-issues#18]
The data or notes sync isn't working between normal and incognito mode!

I saved a link on the Twitter.com page but cannot access it on the same domain page in the Incognito mode of browse page!

**Comment by manugarg** [comment]
I am not sure about sync behavior between Incognito mode and regular mode. I'll take a look, but my current priority is to migrate the extension to manifest v3: #21.

**Comment by drveresh** [comment]
> I am not sure about sync behavior between Incognito mode and regular mode. I'll take a look, but my current priority is to migrate the extension to manifest v3: #21. Let me know if you find anything in the meantime.

Thanks, but please try if you can push these two sets of changes in one shot for publishing.

**Comment by manugarg** [comment]
incognito mode sync is still not priority and I don't believe @drveresh is using this extension anymore.

**Comment by drveresh** [comment]
@manugarg The incognito mode sync is as important as a normal one. FYI, I have been using this extension quite aggressively daily, at least 100+ times a day, both in normal and incognito mode. I don't understand why these important and yet basic features taking years to fix and release.

Anyway, I started building my own extension with much better features and plan to release it soon.

**Comment by manugarg** [comment]
Isn't this you? Stop using this extension. You're a condescending .. I've no desire to engage with you.

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/f08ed375-9c9d-4b96-8d8d-e44c076cb014">

**Comment by drveresh** [comment]
It is not about condescending, but reporting genuine issues. I have been using this for years and did spend a lot of time reporting numerous issues, did give examples to help you inspect and fix if anything.

It works fine 90% of the time, but the rest of the time it fails abruptly. I would share more details if I had enough technical errors that I could capture off your extension. If not, the issue is still relevant, please understand this. Just because it is working for you doesn't mean it should work for everybody else in the world. This is not the ideal and formal way to treat the reported bugs. Also, when the errors or issues is not clear it doesn't mean that we should ignore such issues, instead it's a strong indication that we have to try and evaluate alternate designs or approaches that would address those issues and reduce the probability of errors.

Instead of taking it professionally, why are you taking it personally? What is the relevance of shame here? There is no question of hate here, if so I should have removed it years back, but I am still using it and be using it further with the hope that you will improve it as a standard developer practice, not just for myself, but other community users who are using your extension. I am extremely responsible for reporting, supporting, and helping things get fixed, but I never take it personally.

Lastly, it is probably a privacy violation by keeping that screenshot containing my photo and full name instead of just responding to these comments threads, so please remove it!

**Comment by manugarg** [comment]
I've cropped out your picture out if that's what you're worried about. As I said, I can't entertain your requests anymore. Use it if you want it, or don't use it. I don't have time to deal with your requests and your attitude.

**Comment by manugarg** [comment]
This is my previous comment, to which Veeresh responded above. I deleted the old comment as it a had screenshot with Veeresh's picture and he didn't want it.

--
Isn't this you? Stop using this extension. I've no desire to engage with you.

Moreover, have you no shame? Why do you use it if you hate it so much and you can yourself build it so much better. Just build it. Stop harassing other people.

<img width="969" alt="image" src="https://github.com/user-attachments/assets/9e5dda3b-4479-4a3d-871e-289cc1326928">

**Comment by drveresh** [comment]
@manugarg Please remove the entire screenshot as it contains my full name and those objectionable keywords "shame, hate, harassing", because none of my statements doesn't mean it, but I professionally responded with details using clean language.

**Comment by manugarg** [comment]
@drveresh Your name is in your Github profile and those words are mine -- that's how I perceive your comments. You've given your clarification. I just don't agree with it.

Note: I don't want to interact with you ever again. I am responding now because you think it's a privacy issue. Just clarifying it's not.

**Comment by drveresh** [comment]
@manugarg Again,
1. Why are you questioning somebody else's "**shame**", how is it relevant to this issue?  Does any of my statements denote "shame"?
2. Which of my statements denoted "hate"? I just asked open questions and shared my personal opinion.
3. Which part of the conversation is "harassment"? I neither put pressure nor intimidation to fix it.

It would be decent if you remove those statements and apologize.
