### ISSUE TITLE
Support for kiwi Browser

### ISSUE THREAD

**Issue by FloJ12** [manugarg/pagenotes-issues#20]
Would there be any possibility that you could enable Sync for the Kiwi Browser too?
The extension is working there on android, but if I try to connect it to my google Account for syncing, it always stays on the page where I see the authentication code from google.
If you could add an interface where I could paste the code for the connection, I believe that this would be enough to make it work!

**Comment by manugarg** [comment]
Thanks for filing this @FloJ12. I'll look into this.

**Comment by manugarg** [comment]
This should mostly work now. Let me know if it doesn't.
