### ISSUE TITLE
Google Sync doesn't work on Microsoft Edge (and probably other non-Chrome browsers)

### ISSUE THREAD

**Issue by connectshikha** [manugarg/pagenotes-issues#25]
<img width="791" alt="Screenshot 2023-03-06 at 13 03 15" src="https://user-images.githubusercontent.com/48590878/223046278-7210a27a-d0ac-453c-aaae-98f958556e30.png">

**Comment by manugarg** [comment]
@connectshikha Thanks for filing this.

IIUIC, you're trying to set up sync when this error occurs?

Assuming that, a few questions to debug:

1. Is this the first time you're setting up sync for page notes (including other computers)?
2. How long have you been using page notes? (This is to understand any possible state from the old versions that might be interfering.)
3. My guess is that this extension is somehow in a half state on your machine. Have you tried uninstalling and installing it back? Before doing that please make sure take the backup from the options page. You will be able to restore your notes from that.
4. Are you using any proxy? It's possible proxy is blocking access to certain URLs (e.g. Google Drive). If you're unsure, if you're running this from a corp network, you're likely using proxy. Can you please verify that you can access drive.google.com in your browser.
5. For the first time setup, did you get any popup from Google to authorize Page Notes?

**Comment by connectshikha** [comment]
Hi, 
1. This is the first time I am setting up sync.
2. Around 1-2 weeks
3. I uninstalled it yesterday and then reinstalled, but again could not sync.
4. I am able to access google drive from my browser(MS Edge). I am using my college's internet through LAN, there is a password and username but I am not sure if there is a proxy setting for the internet.
5. I did not get any pop-up from google to authorize page notes.

**Comment by manugarg** [comment]
Interesting. Are you installing this extension on MS Edge? If yes, I am surprised that something like that even works.

**Comment by connectshikha** [comment]
I am using another extension called 'Simple Gmail notes' in MS Edge. The notes made with that extension sync to Google Drive. Can you think of some solution on the similar lines?

**Comment by manugarg** [comment]
@connectshikha Thanks for the reference. I'll try to find out what facilities they are using. It will take some time though.

**Comment by manugarg** [comment]
@connectshikha One more thing, before I attempt this, does rest of the extension work fine in Edge? Features like taking notes, exporting notes, etc.

**Comment by connectshikha** [comment]
Yes, Other features are working fine. I am able to take notes, export and import them.

**Comment by manugarg** [comment]
Thanks for confirming @connectshikha!

Interestingly when I tried to set it up on Edge, I get the explicit error:
![image](https://user-images.githubusercontent.com/1286425/223581480-ab1703a6-68b1-4e14-9cb1-b368e274ab5a.png)

And the URL it points to also make it clear the APIs that are not supported:
https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/api-support#unsupported-extension-apis

Regardless though, I'll try to find if there is an easy fix. It's been ages that I did anything with Microsoft tech.

**Comment by manugarg** [comment]
I believe I got it working, but still working on some final details.

@connectshikha

**Comment by connectshikha** [comment]
Looking forward to it.

**Comment by manugarg** [comment]
@connectshikha just published it. New version is 3.1.0. AFAICT, it's working fine. Can you please give it a try.

If it works, can you please update the extension review (rating and comment)? 😄

**Comment by manugarg** [comment]
@connectshikha I think I spoke too soon. It seems I am not getting refresh token back which is causing browser to ask for authentication again. I'm trying to resolve this issue.

**Comment by manugarg** [comment]
And, now it seem to be working fine. I am not sure what happened last time. Let me know if you run into any problem.

**Comment by manugarg** [comment]
@connectshikha And, now it seem to be working fine. I am not sure what happened last time. Let me know if you run into any problem.

**Comment by connectshikha** [comment]
Thanks for the update. It is syncing with Drive now. I have also updated the review and rating on play store.

**Comment by manugarg** [comment]
Good to know. Thanks!
