### ISSUE TITLE
Autosave and autoedit

### ISSUE THREAD

**Issue by aarrpp** [manugarg/pagenotes-issues#3]
I think that buttons Save and Edit are not needed. 
Autosave and auto-editing much more convenient.

**Comment by erickcampos50** [comment]
I support the request. Removing the "Edit" button will decrease the friction.

**Comment by manugarg** [comment]
Auto-save works already -- button is there but if you close the popup, it saves notes automatically.

**Comment by manugarg** [comment]
This is same as https://github.com/manugarg/pagenotes-issues/issues/13.
