### ISSUE TITLE
Tags on the "All Notes" web page are not alphabetically sorted

### ISSUE THREAD

**Issue by ra5232** [manugarg/pagenotes-issues#38]
Looking for a specific tag is difficult since the tag list is not alphabetically sorted.

**Comment by manugarg** [comment]
@ra5232 I guess I can add an option to sort them alphabetically but just to make it clear they are currently sorted by frequency.

Also, wanted to give you heads up that I am working on adding search to the All Notes page. At the same time "All Notes" page will also become much snappier.

**Comment by manugarg** [comment]
Happy to announce that an option to sort tags alphabetically is coming in the next release. 🎉 🎉
