### ISSUE TITLE
Second sync file created

### ISSUE THREAD

**Issue by erlendorf** [manugarg/pagenotes-issues#39]
Stopped using the extension a couple years ago, but still had the file that was used for syncing with notes in it  in my Google Drive. However, when I just set up sync on my new PC, instead of using the old file, a new, empty, file was created. So I now have two identically named "pagenotes.data" files in the root of my Google Drive. Obviously, I can fix this by copying the contents from the old to the new file, but would be nice if this bug could be fixed.

**Comment by manugarg** [comment]
@erlendorf thanks for filing this. Unfortunately, this is a rather unfixable problem. Some Google-side changes forced us to change the "page notes" client id, which means that the new client cannot find or use the old file. For folks who were using "Page Notes" on a continuous basis, it will not be a problem as local notes will get synced to the new file.

One thing we can likely do is to add a suffix to the pagenotes.data file's name to identify old client vs new client. This will at least avoid the confusion. It will also help with the documentation -- keep this file, delete that file, etc. 

Even though I don't expect any more client changes, this will be a good thing to do anyway.

**Comment by manugarg** [comment]
Now you can import notes from the `pagenotes.data` file directly from the options page. That should solve the problem of importing old notes. You can download the old `pagenotes.data` from Google Drive and import it in your extension.
