### ISSUE TITLE
The Edit button does not work

### ISSUE THREAD

**Issue by ra5232** [manugarg/pagenotes-issues#40]
In the All Notes list, clicking on the Edit button next to any of the Webpages entries does not allow editing that entry.

**Comment by manugarg** [comment]
Much thanks for reporting this @ra5232. Indeed edit functionality got broken in allnotes-prettifying attempt.

I've submitted a fix. It should get release (by Google) in 2-3 days.

**Comment by manugarg** [comment]
Google was quick this item. Fix is already rolled out (release 3.1.6).

Also, alphabetical tags sorting is case insensitive now.

**Comment by ra5232** [comment]
Thank you, Manu!
- Alex.
