### ISSUE TITLE
Make privacy-sensitive permissions optional.

### ISSUE THREAD

**Issue by master0v** [manugarg/pagenotes-issues#5]
Make a version that does not require access to accounts.google.com and/or googleapis.com

<img width="375" alt="Screen Shot 2021-05-15 at 10 07 54 AM" src="https://user-images.githubusercontent.com/18746987/118364212-899ca180-b565-11eb-9b38-1474ea308082.png">

Those permissions should be optional, for people who want to enable cloud sync.  For those of us concerned about privacy, please don't make them default.

**Comment by manugarg** [comment]
@master0v I guess fair enough. I'll prioritize it.

**Comment by manugarg** [comment]
After some thought, I've decided against it. I think it will not create a great experience as sync is a pretty essential part of the extension.

However, privacy-sensitive folks can still disable permission from the extension management page:

<img width="680" alt="image" src="https://github.com/user-attachments/assets/1bc0e195-cb5c-401c-b6a2-b607b0a9bbbd">

I'll add this to the FAQ page.

**Comment by manugarg** [comment]
Note, I am planning to make `accounts.google.com` optional as we don't need it on Chrome anymore.
