### ISSUE TITLE
Dark mode icon

### ISSUE THREAD

**Issue by digyan** [manugarg/pagenotes-issues#50]
Toggle for white icon on dark themes would be great. Pretty much invisible on Chrome dark theme.

![image](https://github.com/manugarg/pagenotes-issues/assets/71324628/cd6ab74f-b57f-4d6d-acab-913460a0fb62)

**Comment by manugarg** [comment]
Thanks for filing this @digyan! I'll take a look.

**Comment by s1awek** [comment]
I'm still having this problem on my machine, will it be looked into?
![2024-09-11_15-46](https://github.com/user-attachments/assets/66a2291f-6c5f-4adc-8a74-cb9faf73ce5d)

**Comment by manugarg** [comment]
Sorry, for not reporting back. I researched and found all the options to implement different icons annoying. There are two options:
- Ask for more permissions to inject a trigger for changing theme.
- Create a different icon -- potentially disruptive.

I'll see what I can do. Thanks for your feedback @s1awek! Please don't hesitate to bump it again in case I don't respond in ~O(days).

**Comment by manugarg** [comment]
@s1awek @digyan Folks, will it be okay if I provide an option to use the dark mode icons? Icons will not switch automatically, but you can set them in options. That we'll not need "scripting" permission and w3c may fix this issue in a few months:
https://github.com/w3c/webextensions/issues/229

**Comment by s1awek** [comment]
> Folks, will it be okay if I provide an option to use the dark mode icons? 

For me it's ok, just wondering if it will be obvious to other users who install your extension?

**Comment by manugarg** [comment]
@s1awek I am really not sure, but if someone wants it they will have an option. As I said earlier, I am hoping w3c will get implemented for chrome soon. Last week only it got implemented for safari and chrome has been supportive for a while now.

<img width="296" alt="image" src="https://github.com/user-attachments/assets/1411bc3d-3729-4125-922c-c147a1dbda53">

**Comment by s1awek** [comment]
Sure, for me this solution is ok :)

**Comment by manugarg** [comment]
I've prepared icons (hopefully good enough). I'll push it soon after some more testing.

**Comment by manugarg** [comment]
I've submitted a new package to chrome webstore - version 3.2.9. It will likely take some time to get reviewed

**Comment by manugarg** [comment]
@s1awek, @digyan 

It's published now. Please give it a try if whenever you get a chance.

**Comment by manugarg** [comment]
I've now automated it using `offscreen` api. If you leave 'Use dark mode icons` setting to 'Auto', extension will automatically switch to dark mode icons if system settings change:
https://pagenotes.manugarg.com/faq/#dark_mode_icon
