### ISSUE TITLE
Not showing the notes

### ISSUE THREAD

**Issue by nurp** [manugarg/pagenotes-issues#52]
I can see the URL and the note in the pagenotes.data file but it is not showing when I visit the page. It shows empty.
I use Chrome, up to date, on MacOS. 
When I look at the options page, it says it is synced 3 minutes ago and it shows all the notes there.

**Comment by nurp** [comment]
Ok, sorry I thought it uses the file from Google Drive. Somehow I couldn't manage to merge it into the new storage space I guess.

**Comment by nurp** [comment]
Not an issue

**Comment by manugarg** [comment]
If you had an old setup (prior to Nov 2021 I believe, see this: https://github.com/manugarg/pagenotes-issues/wiki/Change-in-OAuth-client-for-Google-Drive-sync), it's possible for there to be two `pagenotes.data` files. Usually data gets transferred (old pagenotes to local copy, and then local copy to new pagenotes) correctly, but in some cases there may be issues.

Regarding your previous question:
1. Data in pagenotes.data is basically the cloud copy. Data regularly gets synced between local copy and the remote copy
2. Extension always refers to the local data when reading-writing notes. All notes page (within extension) also looks at the local data.

Hope that clarifies things. Please let me know if there is still an issue.

Cheers,
Manu
