### ISSUE TITLE
Sync not possible using Vivaldi (and maybe also Brave)

### ISSUE THREAD

**Issue by ChristWeiss** [manugarg/pagenotes-issues#53]
Trying to setup sync in Vivaldi gives one of the following errors:

"No Oauth token found" or "The user turned off browser signin"

According to my quick lookup in Google this seems to be related to an unsupported Google API in browsers like Vivaldi or Brave.

If no workaround for this is possible, could an alternative method for syncing be added to the extension (FTP, Dropbox, ...)

I would like to stop using Chrome and switch to an alternative but my notes are very important for my work and I don't want to use Page Notes without the possibility to sync the data file for backup purposes...

I would be glad if you could look into this issue - thanks a lot.

**Comment by manugarg** [comment]
Hi @ChristWeiss, I can confirm that Page Notes works on Brave. I'll check on Vivaldi as well.

**Comment by manugarg** [comment]
Setting up sync on Vivaldi fails, but https://pagenotes.app works. I'll try to find out what's going on, but my initial guess is that Vivaldi is 'looking' too much like Chrome.

**Comment by manugarg** [comment]
Yes, that's the problem. Vivaldi has 'Google Chrome' brand, making extension use the same authentication method as Chrome (while Chrome authentication method is different and dictated by Chrome Web Store policies).

```
navigator.userAgentData.brands
{brand: 'Chromium', version: '124'}
{brand: 'Google Chrome', version: '124'}
{brand: 'Not-A.Brand', version: '99'}
```

I'll try to figure out another way to distinguish Chrome.

**Comment by manugarg** [comment]
A simple fix for Vivaldi is to change the brand the reported.

<img width="1000" alt="image" src="https://github.com/manugarg/pagenotes-issues/assets/1286425/29c6b9f3-4953-4a97-a084-de2dc1978a33">

Brave uses 'Brave' brand and doesn't provide an easy way to change it.

Let me know if this (changing reported brand from 'Google Chrome' to 'Vivaldi') works for you. You'll need to restart the browser after changing it. 

I'll keep looking but it seems there are not many good ways to figure out which browser it is, especially if browsers masquerade (like Vivaldi).

**Comment by ChristWeiss** [comment]
This worked without a problem and is a sufficient solution for me - there shouldn't be many cases where it is necessary for Vivaldi to send Google Chrome as a user agent...

Thanks for your really quick help, it is appreciated

**Comment by JCDC85** [comment]
I just came here looking for a solution to why Vivaldi wasn't working. Changing the brand to Vivaldi, which was previously Chrome, fixed it. Thank you.
I have Brave as well, and it worked with no troubleshooting or adjustments needed.

**Comment by manugarg** [comment]
yeah, I think Brave doesn't identify as Chrome by default. I'll add a FAQ entry about this.
