### ISSUE TITLE
Recovering notes from old chrome profile?

### ISSUE THREAD

**Issue by Protest555** [manugarg/pagenotes-issues#54]
Hello.
My pagenotes sync was turned off. And after chrome reinstallation I lost all my notes. But I kept old chrome profile folder (C:\Users\<UserName>\AppData\Local\Google\ - this one). So i wonder where pagenotes keeps its data locally and is it possible to recover my notes now, after I reinstalled web browser? 
Thank you

**Comment by manugarg** [comment]
1. Did you sync your notes to Google Drive?
If yes, you should be able to update your local copy using sync.

2. Can you restart browser with the old profile?
If yes, you can export your notes (from options) and import them back in the new profile (from options page).

**Comment by Protest555** [comment]
Sync was off, but I will try to launch chrome with my old profile. Thank you for suggestion
